services:
  #Your services which are postgres and Mongo should be named with your First and Last Names
  First:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
#Your DB should be named after your ID
      - POSTGRES_DB=52_1234


  Last:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  app:
    build: .
    depends_on:
      - Mohamed
      - Ayman
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/52_1234
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      spring.data.mongodb.uri: mongodb://root:example@mongo:27017/mini_mongo?authSource=admin
      spring.data.mongodb.username: root
      spring.data.mongodb.password: example
      #Your DB should be named after your ID

      spring.data.mongodb.database: 52_1234